language: c
script:
- if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./util/continuous-build.sh; fi
compiler:
- gcc-4.8
env:
  global:
  - ARCH=amd64
  - HARVEY=$TRAVIS_BUILD_DIR
  - PATH=$PATH:$HARVEY/util
  - secure: QnzPjsNkXKz3yMt1ySIdlwFcKUlykgP+FP5MWTK0fijZD+8tKY9cN+X8010AWXKdy1OxJt1THWBpgMDl3rPe1msnWP+WNX2bGG5lfGsky4EB4tD7LEXRJaVp3JNrxoK9lGCcpKi7b2i8AKmBDZoVVZ3gMQpXvr/Il432bKauSrYugsgMwUbx6IyLz5zamSc6NhiB+onwjSJ/mN09WZ6mZVXzEGFxvI0REKyt/BqPD7sI6JzUl5A3yoXJT18jXerawvub/NeTB5rCDpL8CJBI9cQ/zAR4kg31vu4q4551jXj5XU8BXbWtV7562EGFE/z9W9CLmy7vqu+DM6UP6+P5OlqLy7RBpgNNFhmxpePzEe2bEMhYC94FKyiMdsKOb/Ddd1fF4iuR0aPKZ9cRlqMdnrpLgwfntSSvLGnYpwMdOr/h2gYKPbzPz0HVAIK/EU+nbAo1cY6TtS5qMZtu9AkOiVqEGIfhGVIBtOarqntEjDHRD5Fy6Fcl7uZc3vldudVOfVPEla5bD5eD3VLqDch12yLRoJp2rWBg9oyVw5hdM5nsInCagtvSFM9AfgIv8cwOFl5BNd3/wWw1J7Sd21jxRt9bzvKRqLJduJ2TgXkpkoSCq/yHUDoPkh+HnkeoXqNvsxMR64NHU2pEBVLCCmQrWHRdFzH9hGEbebQL3gRSY7o=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - rc
    - gcc-4.8
  coverity_scan:
    project:
      name: Shamar/harvey
      description: Build submitted via Travis CI
    notification_email: harvey@googlegroups.com
    build_command_prepend: "./bootstrap.sh"
    build_command: source envsetup && build all
    branch_pattern: coverity_scan*
